### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by LouisNoailles** [sylefeb/LibSL#15]
Hi,

While trying to compile LibSL-small, it appears to be missing th file libjpeg.h which is in LibSL and not in the small version.
Is it normal ? How can I fix this issue.

Regards,

**Comment by sylefeb** [comment]
Hi LouisNoailles,

LibSL-small ( https://github.com/sylefeb/LibSL-small/ )  is meant to be a tiny subset of LibSL focusing on core functionalities and having as little dependencies as possible. The jpg image format files are included but -- by default -- only linked under Linux where libjpeg is usually on the system (see https://github.com/sylefeb/LibSL-small/blob/master/CMakeLists.txt ). In what context are you compiling LibSL-small? (platform, compiler, etc.)

Best regards -
PS: This issue would be best in the LibSL-small repo as it does not concern LibSL 'full'.

**Comment by LouisNoailles** [comment]
Ok I just forgot the fact that it is an external lib sorry for this issue
